// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "vulcan_lcm_imu_t.h"

static int __vulcan_lcm_imu_t_hash_computed;
static uint64_t __vulcan_lcm_imu_t_hash;

uint64_t __vulcan_lcm_imu_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __vulcan_lcm_imu_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__vulcan_lcm_imu_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xca3c68d737b34951LL
         + __int64_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __vulcan_lcm_imu_t_get_hash(void)
{
    if (!__vulcan_lcm_imu_t_hash_computed) {
        __vulcan_lcm_imu_t_hash = (int64_t)__vulcan_lcm_imu_t_hash_recursive(NULL);
        __vulcan_lcm_imu_t_hash_computed = 1;
    }

    return __vulcan_lcm_imu_t_hash;
}

int __vulcan_lcm_imu_t_encode_array(void *buf, int offset, int maxlen, const vulcan_lcm_imu_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].sequence_number), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].time_delta), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].accel, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].rotational_vel, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].orientation, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].gravity), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int vulcan_lcm_imu_t_encode(void *buf, int offset, int maxlen, const vulcan_lcm_imu_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __vulcan_lcm_imu_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __vulcan_lcm_imu_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __vulcan_lcm_imu_t_encoded_array_size(const vulcan_lcm_imu_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].timestamp), 1);

        size += __int32_t_encoded_array_size(&(p[element].sequence_number), 1);

        size += __int32_t_encoded_array_size(&(p[element].time_delta), 1);

        size += __float_encoded_array_size(p[element].accel, 3);

        size += __float_encoded_array_size(p[element].rotational_vel, 3);

        size += __float_encoded_array_size(p[element].orientation, 3);

        size += __float_encoded_array_size(&(p[element].gravity), 1);

    }
    return size;
}

int vulcan_lcm_imu_t_encoded_size(const vulcan_lcm_imu_t *p)
{
    return 8 + __vulcan_lcm_imu_t_encoded_array_size(p, 1);
}

int __vulcan_lcm_imu_t_decode_array(const void *buf, int offset, int maxlen, vulcan_lcm_imu_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].sequence_number), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].time_delta), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].accel, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].rotational_vel, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].orientation, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].gravity), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __vulcan_lcm_imu_t_decode_array_cleanup(vulcan_lcm_imu_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].timestamp), 1);

        __int32_t_decode_array_cleanup(&(p[element].sequence_number), 1);

        __int32_t_decode_array_cleanup(&(p[element].time_delta), 1);

        __float_decode_array_cleanup(p[element].accel, 3);

        __float_decode_array_cleanup(p[element].rotational_vel, 3);

        __float_decode_array_cleanup(p[element].orientation, 3);

        __float_decode_array_cleanup(&(p[element].gravity), 1);

    }
    return 0;
}

int vulcan_lcm_imu_t_decode(const void *buf, int offset, int maxlen, vulcan_lcm_imu_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __vulcan_lcm_imu_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __vulcan_lcm_imu_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int vulcan_lcm_imu_t_decode_cleanup(vulcan_lcm_imu_t *p)
{
    return __vulcan_lcm_imu_t_decode_array_cleanup(p, 1);
}

int __vulcan_lcm_imu_t_clone_array(const vulcan_lcm_imu_t *p, vulcan_lcm_imu_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].timestamp), &(q[element].timestamp), 1);

        __int32_t_clone_array(&(p[element].sequence_number), &(q[element].sequence_number), 1);

        __int32_t_clone_array(&(p[element].time_delta), &(q[element].time_delta), 1);

        __float_clone_array(p[element].accel, q[element].accel, 3);

        __float_clone_array(p[element].rotational_vel, q[element].rotational_vel, 3);

        __float_clone_array(p[element].orientation, q[element].orientation, 3);

        __float_clone_array(&(p[element].gravity), &(q[element].gravity), 1);

    }
    return 0;
}

vulcan_lcm_imu_t *vulcan_lcm_imu_t_copy(const vulcan_lcm_imu_t *p)
{
    vulcan_lcm_imu_t *q = (vulcan_lcm_imu_t*) malloc(sizeof(vulcan_lcm_imu_t));
    __vulcan_lcm_imu_t_clone_array(p, q, 1);
    return q;
}

void vulcan_lcm_imu_t_destroy(vulcan_lcm_imu_t *p)
{
    __vulcan_lcm_imu_t_decode_array_cleanup(p, 1);
    free(p);
}

int vulcan_lcm_imu_t_publish(lcm_t *lc, const char *channel, const vulcan_lcm_imu_t *p)
{
      int max_data_size = vulcan_lcm_imu_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = vulcan_lcm_imu_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _vulcan_lcm_imu_t_subscription_t {
    vulcan_lcm_imu_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void vulcan_lcm_imu_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    vulcan_lcm_imu_t p;
    memset(&p, 0, sizeof(vulcan_lcm_imu_t));
    status = vulcan_lcm_imu_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding vulcan_lcm_imu_t!!!\n", status);
        return;
    }

    vulcan_lcm_imu_t_subscription_t *h = (vulcan_lcm_imu_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    vulcan_lcm_imu_t_decode_cleanup (&p);
}

vulcan_lcm_imu_t_subscription_t* vulcan_lcm_imu_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    vulcan_lcm_imu_t_handler_t f, void *userdata)
{
    vulcan_lcm_imu_t_subscription_t *n = (vulcan_lcm_imu_t_subscription_t*)
                       malloc(sizeof(vulcan_lcm_imu_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 vulcan_lcm_imu_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg vulcan_lcm_imu_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int vulcan_lcm_imu_t_subscription_set_queue_capacity (vulcan_lcm_imu_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int vulcan_lcm_imu_t_unsubscribe(lcm_t *lcm, vulcan_lcm_imu_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe vulcan_lcm_imu_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

